### ISSUE TITLE
Support running on Windows

### ISSUE THREAD

**Issue by Robpol86** [z4r/python-coveralls#26]
I'm looking into using [AppVeyor](http://www.appveyor.com/) to test my projects on Windows. While testing locally I get this error during pip install:

```
Downloading/unpacking sh (from python-coveralls)
  Downloading sh-1.09.tar.gz
  Running setup.py (path:C:\Users\Robpol86\AppData\Local\Temp\pip_build_Robpol86\sh\setup.py) egg_info for package sh
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "C:\Users\Robpol86\AppData\Local\Temp\pip_build_Robpol86\sh\setup.py", line 4, in <module>
        import sh
      File "C:\Users\Robpol86\AppData\Local\Temp\pip_build_Robpol86\sh\sh.py", line 34, in <module>
        support." % __version__)
    ImportError: sh 1.09 is currently only supported on linux and osx. please install pbs 0.110 (http://pypi.python.org/pypi/pbs) for windows support.
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "C:\Users\Robpol86\AppData\Local\Temp\pip_build_Robpol86\sh\setup.py", line 4, in <module>

    import sh

  File "C:\Users\Robpol86\AppData\Local\Temp\pip_build_Robpol86\sh\sh.py", line 34, in <module>

    support." % __version__)

ImportError: sh 1.09 is currently only supported on linux and osx. please install pbs 0.110 (http://pypi.python.org/pypi/pbs) for windows support.
```

**Comment by haileyl** [comment]
This is how cargo-lite fixed this issue.

https://github.com/cmr/cargo-lite/commit/36df33157a496503a2ada074df3b77703091f81d
