### ISSUE TITLE
Support for coverage 4.0

### ISSUE THREAD

**Issue by jorisroovers** [z4r/python-coveralls#39]
python-coveralls doesn't like coverage 4.0:

```
$ coveralls
Traceback (most recent call last):
  File "/vagrant/.venv/bin/coveralls", line 11, in <module>
    sys.exit(wear())
  File "/vagrant/.venv/local/lib/python2.7/site-packages/coveralls/__init__.py", line 76, in wear
    from coveralls.control import coveralls
  File "/vagrant/.venv/local/lib/python2.7/site-packages/coveralls/control.py", line 1, in <module>
    from coverage.control import coverage
ImportError: cannot import name coverage
```

I ended up downgrading back to coverage 3.7.1 for the time being.

**Comment by z4r** [comment]
Im sorry, but these days i've no time to take a look in this issue.

Could someone help me with a Pull Request? ;)

**Comment by jakirkham** [comment]
This is already. Should it be closed?

https://github.com/z4r/python-coveralls/blob/286e98ff8d3aebc2b78659fa0dd08a575a7a7285/setup.py#L25
