### ISSUE TITLE
python-coveralls 2.6.0 requires .coveragerc file

### ISSUE THREAD

**Issue by RevolutionTech** [z4r/python-coveralls#45]
If the user does not have a `.coveragerc` file in their repo, `coveralls` command fails with:
```bash
$ coveralls
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.9/bin/coveralls", line 11, in <module>
    sys.exit(wear())
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/coveralls/__init__.py", line 86, in wear
    coverage = coveralls(data_file=args.data_file, config_file=args.config_file)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/coverage/control.py", line 140, in __init__
    "Couldn't read '%s' as a config file" % config_file
coverage.misc.CoverageException: Couldn't read '/home/travis/build/<TRAVISUSER>/<PATH>/.coveragerc' as a config file
```

Perhaps this is regression introduced by changes in the coverage 4.0 API?

**Comment by bintoro** [comment]
This has been fixed by #46, I believe. Hoping for a release to land on PyPI soon. :relaxed:

**Comment by z4r** [comment]
2.7.0 up and running ;)

**Comment by RevolutionTech** [comment]
Thanks so much for fixing this!
