### ISSUE TITLE
Attempting to injest coverage report into '--data_file'

### ISSUE THREAD

**Issue by jeff1evesque** [z4r/python-coveralls#59]
I've generated a coverage report from my flask [`app.py`](https://github.com/jeff1evesque/machine-learning/blob/00fce3b9b1587e13493d63398fa1a07770492414/app.py#L21-L25) as follows:

```python
        pytest.main([
            '--cov', '.',
            '--cov-report', 'xml:/var/machine-learning/coverage.xml',
            'test/live_server'
        ])
```

**Note:** the above syntax was predicated on my [installing](https://github.com/jeff1evesque/machine-learning/blob/bdf8cdcce1b8fcb9efd8c0fbffa599c124bd647f/default.dockerfile#L31) the `pytest-cov` package.

Since this report is generated from a docker container, spun up by travis ci, I needed to redirect the output to the above indicated `/var/machine-learning/coverage.xml`.  However, this file needed to be [copied](https://github.com/jeff1evesque/machine-learning/blob/f68c2acd5edaeb233097b6455aa2f4eaeca12f2b/.travis.yml#L118) from the docker container, to the ubuntu 14.04 host, running the docker unit testing environment:

```yaml
 - docker cp webserver-pytest:/var/machine-learning/coverage.xml coverage.xml
```

So, I proceeded to [injest](https://github.com/jeff1evesque/machine-learning/blob/f68c2acd5edaeb233097b6455aa2f4eaeca12f2b/.travis.yml#L129-L131) this `coverage.xml` into the `coveralls` command:

```yaml
## post build: the following commands are run after a successful, or failed build.
after_success:
  - coveralls --data_file=coverage.xml
```

**Note:** the generated `coverage.xml` can be [reviewed](https://travis-ci.org/jeff1evesque/machine-learning/builds/192214255#L4094-L6722) within the `.travis.yml` output.

This generated the following [traceback](https://travis-ci.org/jeff1evesque/machine-learning/builds/192214255#L6751-L6763) when travis ci ran:

>$ coveralls --data_file=coverage.xml
>
>Traceback (most recent call last):
>
>  File "/home/travis/virtualenv/python2.7.12/bin/coveralls", line 11, in <module>
>
>    sys.exit(wear())
>
>  File "/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/coveralls/__init__.py", line 87, in wear
>
>    coverage.load()
>
>  File "/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/coverage/control.py", line 664, in load
>
>    self.data_files.read(self.data)
>
>  File "/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/coverage/data.py", line 636, in read
>
>    data.read_file(self.filename)
>
>  File "/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/coverage/data.py", line 295, in read_file
>
>    filename, exc.__class__.__name__, exc,
>
>coverage.misc.CoverageException: Couldn't read data from '/home/travis/build/jeff1evesque/machine-learning/coverage.xml': CoverageException: Doesn't seem to be a coverage.py data file

**Note:** the above problem is associated with an [existing issue](https://github.com/jeff1evesque/machine-learning/issues/2697), which has commits that can be reviewed.

**Comment by jeff1evesque** [comment]
The pytest-cov [documentation](http://pytest-cov.readthedocs.io/en/latest/readme.html#reporting) states the following:

>These three report options output to files without showing anything on the terminal:
>
>```python
>    py.test --cov-report html
>               --cov-report xml
>               --cov-report annotate
>               --cov=myproj tests/
>```
>
>The output location for each of these reports can be specified. The output location for the XML report is
>a file. Where as the output location for the HTML and annotated source code reports are directories:
>
>```python
>py.test --cov-report html:cov_html
>           --cov-report xml:cov.xml
>           --cov-report annotate:cov_annotate
>           --cov=myproj tests/
>```
>
>The final report option can also suppress printing to the terminal:
>
>```python
>py.test --cov-report= --cov=myproj tests/
>```
>
>This mode can be especially useful on continuous integration servers, where a coverage file is needed 
>for subsequent processing, but no local report needs to be viewed. For example, tests run on Travis-CI >could produce a .coverage file for use with Coveralls.

Can I somehow use the options pytest-cov provides (i.e. redirecting report), as an input to python-coveralls `--data_file` flag?

**Comment by jeff1evesque** [comment]
I changed my implementation by generating `.coverage`, instead of my previous `coverage.xml`.  However, the report was generated from my docker container (spun up by travis), then copied into the travis environment.  I didn't plan on running the `coverage` or equivalent command from my `script` directive in the `.travis.yml` file, since a corresponding `.coverage` file has already been generated in the docker container, then copied into the VM hosting travis.  I was hoping there would be some nifty command I could run in the `after_success` directive in the [`.travis.yml`](https://github.com/jeff1evesque/machine-learning/blob/ec23e2bfd96e366204bb35d2fb4a66d7ced4dda9/.travis.yml#L132), which would properly submit this coverage report to [coveralls](https://coveralls.io/github/jeff1evesque/machine-learning), after a travis build finished.  Could someone assist me wiring this up?

**Comment by jeff1evesque** [comment]
I received much [help](https://github.com/pytest-dev/pytest-cov/issues/146#issuecomment-272977522) from the [pytest-cov](https://github.com/pytest-dev/pytest-cov) repository, and have [coveralls](https://coveralls.io/github/jeff1evesque/machine-learning) working now.

**Comment by jeff1evesque** [comment]
If anyone is curious in the future how a coverage report generated from a docker container was able to be copied to the travis environment, to subsequently generate corresponding report on coveralls, feel free to review the corresponding [pull request](https://github.com/jeff1evesque/machine-learning/pull/2874) I have submitted, on the [machine-learning](https://github.com/jeff1evesque/machine-learning) repository.
