### ISSUE TITLE
TypeError: CoverallsReporter() takes no arguments

### ISSUE THREAD

**Issue by VovaMazur** [z4r/python-coveralls#79]
Dear Sirs,

Trying to setup coveralls for pretty simple flask web app.
UT is done with coverage / unittest.

After the successful built (with TravisCI), coveralls command shows below error:
Traceback (most recent call last):
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Documents\EPAM\Pet_projects\Python EPAM stream\venv\Scripts\coveralls.exe\__main__.py", line 7, in <module>
  File "D:\Documents\EPAM\Pet_projects\Python EPAM stream\venv\lib\site-packages\coveralls\__init__.py", line 93, in wear
    source_files=coverage.coveralls(args.base_dir, ignore_errors=args.ignore_errors, merge_file=args.merge_file),
  File "D:\Documents\EPAM\Pet_projects\Python EPAM stream\venv\lib\site-packages\coveralls\control.py", line 7, in coveralls
    reporter = CoverallsReporter(self, self.config)
TypeError: CoverallsReporter() takes no arguments

***
**Travis.yml script:**

language: python
python:
  - "3.9"      # current default Python on Travis CI

install:
  - pip install -r requirements.txt

script:
  - pylint --exit-zero manifestapp
  - coverage run -m unittest tests
  - coverage report

after_success:
  - coveralls

**Comment by bfontaine** [comment]
I encountered this error as well on [xtools](https://github.com/bfontaine/xtools/blob/81af00a210db091dd48852b65da876f3336befdf/.github/workflows/build.yml#L36). The issue is that python-coveralls depends on [`coverage`](https://github.com/z4r/python-coveralls/blob/e5f5eb81e62b5b2b38244721325be194937f22fe/setup.py#L25) without specifying any version, so if `coverage` introduces breaking changes, like it did in the release 5.0.0 that removed the [`Reporter` class](https://github.com/nedbat/coveragepy/blob/coverage-4.5.4/coverage/report.py#L15), everything breaks.

Until this library is fixed, the solution is to downgrade `coverage` to 4.5.4. If you use `pytest-cov`, you’ll have to downgrade it as well to the last version that supported `coverage<5.0`, i.e. [2.10.1](https://pytest-cov.readthedocs.io/en/latest/changelog.html#id34).

If you use Poetry, this is the solution:

```bash
poetry remove pytest-cov
poetry add --group dev coverage@4.5.4
poetry add --group dev pytest-cov@2.10.1
```
